# Generated by Django 2.2 on 2019-05-25 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('razon_social', models.CharField(max_length=80, verbose_name='Razón Social')),
                ('rif', models.CharField(max_length=12, verbose_name='RIF')),
                ('direccion', models.CharField(max_length=120, verbose_name='Dirección')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='config.Ciudad')),
                ('vendedor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='venta.Vendedor')),
                ('zona', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='config.Zona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
